### PR TITLE
fix: add `Generator` return type to `PageIterator.search`

### PR DESCRIPTION
**Pull request by omBratteng**
Should probably fix this issue encountered in this comment https://github.com/vemel/mypy_boto3_builder/issues/106#issuecomment-959758254

### CODE REVIEW

**Review by vemel — APPROVED** [review]

**Comment by omBratteng** [comment]
That could probably work. Generator[Any, None, None] is what VS Code hinted as return type.
I could test with Iterator and see if mypy agrees.

**Comment by vemel** [comment]
I have just checked. Please update your PR.

**Comment by omBratteng** [comment]
I just testet myself. Just wondering if Iterator is correct, though it works. `PageIterator.search` yields the result.
Just a question.
```python
def search(self, expression):
    compiled = jmespath.compile(expression)
    for page in self:
        results = compiled.search(page)
        if isinstance(results, list):
            for element in results:
                yield element
        else:
            # Yield result directly if it is not a list.
            yield results
```

**Comment by vemel** [comment]
Looks good to me! Please update your code.

**Comment by omBratteng** [comment]
Replaced Generator with Iterator

**Pull request merged**
