### PR TITLE
Pre-generated stubs for all services

### PR DESCRIPTION
**Pull request by vemel**
## Notes

The main goal is to fully support `pyright` while keeping `mypy` performance as good as it can be. `PyCharm` performance is no longer a priority, so use any other Python Language Server (`pylance` or `jedi`) for type checking and auto-complete.

DoD: both `mypy` and `pyright` suppot implicit type annotations, produce similar results and have decent performance

## Tools support

Since we now have 300+ overloads in both `boto3` and `boto3.session` files, it makes sense to keep track of performance and discovery issues. All checks are done with implicit type annotations.

`pyright` - very fast, all types are discovered correctly, dirty hacks like `client.exceptions` are not working
`mypy` - performance is slightly worse, but still usable, all types are discovered correctly
`PyCharm` - not tested yet
`jedi` - support for `Literal` overloads is not fully implemented, implicit type annotations are not working
`vscode` - support for `Literal` overloads is not fully implemented, implicit type annotations are not working

## TODO

- [x] Remove internal imports in stub files, so `pyright` always finds type annotations correctly
- [x] Pre-generate all overloads, implicit type annotations should be fully supported
- [x] Convert all stub `py` fles to `pyi` for correct discovery
- [x] Fix`client`/`resource` argument type annotations if passing `None` is safe
- [x] Fix `client.extensions` not being processed by `pyright` correctly
- [x] Deprecate `mypy_boto3` package or even remove it
- [x] Update docs
- [x] Check `PyCharm` permormance

### Changed

- All type stubs were converted to `pyi` files (pyright support)
- `boto3.client/resource` overloads for all services are pre-generated, which renders `mypy_boto3` CLI useless
- `Session.client/resource` overloads for all services are pre-generated, which renders `mypy_boto3` CLI useless
- Updated `black+isort` for generated files

### Fixed

- Imports were sorted incorrectly in generated `boto3-stubs`
- Some imports were incorrectly marked as unused by `pylint`
- `botocore.client.ClientError` is correctly handled by `pyright`

### CODE REVIEW

**Comment by tekumara** [comment]
I can try testing this with PyCharm if you like (I have a few colleagues using PyCharm)?

**Comment by vemel** [comment]
@tekumara I would appreciate it

The easiest way:

```
pip install pipenv

git clone git@github.com:vemel/mypy_boto3_builder.git
cd mypy_boto3_builder
pipenv install -d
pipenv shell

./scripts/build.sh -s s3 # for example, let's buld just master packages and s3 service package
./scripts/install.sh master
./scripts/install.sh s3

# select virtualenv created by pipenv, and test type checking and auto-complete in `examples` forder
```

**Comment by tekumara** [comment]
Thanks for detailed instructions, that was helpful!

PyCharm perf seems fine to me! 

A couple of things I noticed:

1. pyright in strict mode couldn't find the stub files eg: 
```
Stub file not found for "mypy_boto3_s3"
Stub file not found for "mypy_boto3_ec2"
```
### s3_example.py

2. pyright produces `error: "session" is not a known member of module` for:
```python
session = boto3.session.Session(region_name="us-west-1")
```
(PyCharm has no problem with this snippet)

### ec2_example.py

3. In pyright Type of "resource" is unknown
```python
resource: EC2ServiceResource = session.resource("ec2")
```

4. In pyright the type `vpc_peer.accepter_vpc` is Unknown, but PyCharm correctly detects 
```python
vpc_peer.accepter_vpc.delete("incorrect")
```

5. In pyright Type of "region_name" is unknown
```python
region_name = client.meta.region_name
```

6. For this snippet, BaseClient is being inferred rather than S3Client (in both PyCharm and pylance/pyright)
```python
client: EC2Client = boto3.client("ec2")
```

**Comment by vemel** [comment]
Hmm, are you using examples from `v3-pyright` branch? I think i fixed `boto3.session.Session` import. Also, there should be no type annotations, they have to be picked up automatically.

Regarding `accepter_vpc` -  should take a look.

Thank you a lot!

**Comment by tekumara** [comment]
Oh dear, I missed the `git checkout v3-pyright` step 🤦‍♀️ ignore everything I said above, and let me try that again ...

So now with the `v3-pyright` branch, Pycharm is not so happy. At one point my CPU got warm thanks to Pycharm 🥵 . There's a noticeable delay of several seconds to typecheck a file once opened. And the types for the expression `client = boto3.client("s3")` are no longer inferred or autocompleted (I believe they used to be).

The type errors that look a bit unexpected in pyright are:

*ec2_example.py*

>   17:5 - error: Argument missing for parameter "Resources" (reportGeneralTypeIssues)
>   17:31 - error: Argument of type "Literal[123]" cannot be assigned to parameter "Tags" of type "List" in function "create_tags"
>   "Literal[123]" is incompatible with "List[TagTypeDef]" (reportGeneralTypeIssues)

*s3_example.py*

>   65:17 - error: Cannot access member "operations_name" for type "ClientError"

An in pyright strict mode:

*ec2_example.py*
>  10:16 - error: Type of "resource" is partially unknown
>  11:17 - error: Type of "resource" is partially unknown

I'm guessing this is because most of the overloads are returning clients that I haven't built and installed? The type error generated is very long and includes every single overload 😅

And in pylint:

*dynamodb_example.py*

> examples/dynamodb_example.py:7:0: E0611: No name 'DynamoDBClient' in module 'mypy_boto3_dynamodb' (no-name-in-module)
> examples/dynamodb_example.py:7:0: E0611: No name 'DynamoDBServiceResource' in module 'mypy_boto3_dynamodb' (no-name-in-module)
> examples/dynamodb_example.py:8:0: E0611: No name 'service_resource' in module 'mypy_boto3_dynamodb' (no-name-in-module)
> examples/dynamodb_example.py:8:0: E0401: Unable to import 'mypy_boto3_dynamodb.service_resource' (import-error)

**Comment by vemel** [comment]
`pyright` does not try to guess types from `botocore`. I added `boto3-stubs/botocore_stubs.pyi` file to add annotations for `ClientError`. Probably we need one for `BaseClient` as well.

Pylint is right actually, imports should be `from mypy_boto3_dynamodb.client import DynamoDBClient` and so on. 

Still, this is way better than it was.

**Comment by vemel** [comment]
@tekumara I believe, this is the final version. I checked that it works both in Pylance-powered VSCode and PyCharm 2020.2.1. On my machine autocomplete works, but takes around 2 seconds to show up. This is way better than I expected.

**Comment by tekumara** [comment]
I've tried the latest commit but still get PyCharm overheating, and the same issues as above.

I'm also not sure how to best import the following, which pylint identifies as no-name-in-module and import-error:
```
from mypy_boto3_ec2.type_defs import FilterTypeDef
```

**Comment by vemel** [comment]
I had no issues with `pylint==2.6.0`

How I set up PyCharm:

```bash
git clone ... && git checkout v2-pyright
pipenv install -d && pipenv shell
./scripts/build.sh # this creates `mypy_boto3_output` directory with ready-to-install packages

# create new venv in pycharm, next steps in pycharm terminal with opened git repo
pip install -r requirements.txt
./scripts/install.sh master
./scripts/install.sh s3 # you can install annotations for other packages this way

# open examples/s3_examples.py
# auto-complete should work already as well as type checking
```

Let me know if this works for you. py3.8.5, latest boto3, PyCharm 2020.2.1

**Pull request merged**
